### PR TITLE
Searching slots for 7 consecutive days

### PR DESCRIPTION
**Pull request by Anwit**
Current code does not search slots for next 7 days. Though it is mentioned in the comment: 
"Search for next seven day starting from when?"

Test Output:

Centres are available in Kolkata from 26-05-2021 as of 2021-05-25 15:22:12: 45
Centres are available in Kolkata from 27-05-2021 as of 2021-05-25 15:22:12: 41
Centres are available in Kolkata from 28-05-2021 as of 2021-05-25 15:22:12: 39
Centres are available in Kolkata from 29-05-2021 as of 2021-05-25 15:22:12: 37
Centres are available in Kolkata from 30-05-2021 as of 2021-05-25 15:22:12: 9
Centres are available in Kolkata from 31-05-2021 as of 2021-05-25 15:22:12: 8
Centres are available in Kolkata from 01-06-2021 as of 2021-05-25 15:22:12: 1

### CODE REVIEW

**Comment by dhhruv** [comment]
@Anwit Just want to ask as I won't be getting time to test it completely. Are there any other conflicts after testing this?

**Comment by Anwit** [comment]
no merge conflict.. pulled latest changes.. I am running this script for a day.. Added just a loop here

**Comment by dhhruv** [comment]
Thanks @Anwit

**Comment by Nakul93** [comment]
> Current code does not search slots for next 7 days. Though it is mentioned in the comment:
> "Search for next seven day starting from when?"
> 
> Test Output:
> 
> Centres are available in Kolkata from 26-05-2021 as of 2021-05-25 15:22:12: 45
> Centres are available in Kolkata from 27-05-2021 as of 2021-05-25 15:22:12: 41
> Centres are available in Kolkata from 28-05-2021 as of 2021-05-25 15:22:12: 39
> Centres are available in Kolkata from 29-05-2021 as of 2021-05-25 15:22:12: 37
> Centres are available in Kolkata from 30-05-2021 as of 2021-05-25 15:22:12: 9
> Centres are available in Kolkata from 31-05-2021 as of 2021-05-25 15:22:12: 8
> Centres are available in Kolkata from 01-06-2021 as of 2021-05-25 15:22:12: 1

It does, actually the options for centres available shows the total count of all centres available for the next 7 days starting from the start date. 
It doesn’t display separately as you mentioned above but once viable options are matched they are shown in table format

**Pull request merged**
